# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- fuck-github

pool:
  name: 'HP Omen 2020'

steps:
- script: |
    type index.txt >> index.html
    type index.html
    git add .
    git commit -m "Publishing GitHub Pages  ***NO_CI***"
    git remote set-url --push origin git@github.com:tntxtnt/azure-test.git
    git push origin HEAD:fuck-github
  displayName: 'Publish GitHub Pages'
  condition: |
    and(not(eq(variables['Build.Reason'], 'PullRequest')),
        eq(variables['Build.SourceBranch'], 'refs/heads/fuck-github'))
